name: Publish to NPM registry

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies and Build
        run: yarn --frozen-lockfile
      - name: Tests
        run: yarn test
      - name: Publish to npmjs registry
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
